// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentalsProAPIV8.Models;

public partial class Loan
{
    public int ID { get; set; }

    public int LenderID { get; set; }

    public int LoanTypeID { get; set; }

    public int PropertyID { get; set; }

    public decimal LoanAmount { get; set; }

    public decimal InterestRate { get; set; }

    public int LoanTermMonths { get; set; }

    public DateTime StartDate { get; set; }

    public DateTime DueDate { get; set; }

    public decimal MonthlyPayment { get; set; }

    public decimal RemainingBalance { get; set; }

    public bool Active { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public virtual Lender Lender { get; set; }

    public virtual LoanType LoanType { get; set; }

    public virtual Property Property { get; set; }
}