// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentalsProAPIV8.Models;

public partial class PaymentStatus
{
    public int ID { get; set; }

    public string Name { get; set; }

    public string Color { get; set; }

    public virtual ICollection<Property> Properties { get; set; } = new List<Property>();

    public virtual ICollection<Unit> Units { get; set; } = new List<Unit>();
}