// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentalsProAPIV8.Models;

public partial class Unit
{
    public int ID { get; set; }

    public int PropertyID { get; set; }

    public string UnitNumber { get; set; }

    public int? Floor { get; set; }

    public int SquareFeet { get; set; }

    public string UnitType { get; set; }

    public decimal? Bedrooms { get; set; }

    public decimal? Bathrooms { get; set; }

    public bool? Utilities { get; set; }

    public bool? Furnished { get; set; }

    public bool? ParkingSpace { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool Active { get; set; }

    public int StatusID { get; set; }

    public int PaymentStatusID { get; set; }

    public virtual ICollection<Lease> Leases { get; set; } = new List<Lease>();

    public virtual PaymentStatus PaymentStatus { get; set; }

    public virtual Property Property { get; set; }

    public virtual PropertyStatus Status { get; set; }
}