// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace RentalsProAPIV8.Models;

public partial class User
{
    public int ID { get; set; }

    public int? CompanyID { get; set; }

    public int? LeaseID { get; set; }

    public string Username { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string PasswordHash { get; set; }

    public string PasswordSalt { get; set; }

    public string Email { get; set; }

    public string Phone { get; set; }

    public int Role { get; set; }

    public DateOnly? Birthdate { get; set; }

    public DateTime CreatedDate { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public bool Active { get; set; }

    public bool IsOwner { get; set; }

    public virtual Company Company { get; set; }

    public virtual Lease Lease { get; set; }

    public virtual ICollection<Property> Properties { get; set; } = new List<Property>();
}